- name: Ensure remote host key is in known_hosts
  ansible.builtin.known_hosts:
    path: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
    name: "{{ ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
  delegate_to: localhost
  when: ansible_host not in ['localhost', '127.0.0.1', '::1']

- name: Add Interactive User to Sudoers
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ ansible_user }}"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: true
