- name: Ensure remote host key is in known_hosts
  ansible.builtin.known_hosts:
    path: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
    name: "{{ ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H ' + ansible_host) }}"
  delegate_to: localhost

- name: Test if ssh password works
  ansible.builtin.shell:
    cmd: sshpass -e ssh "{{ ansible_user }}@{{ ansible_host }}" "true"
  environment:
    SSHPASS: "{{ secrets.new_password }}"
  register: ssh_test
  delegate_to: localhost
  ignore_errors: true
  no_log: true

- name: Set Login Password Based on SSH Test
  ansible.builtin.set_fact:
    ansible_become_password: "{{ secrets.new_password if ssh_test.rc == 0 else secrets.temp_password }}"
    ansible_password: "{{ secrets.new_password if ssh_test.rc == 0 else secrets.temp_password }}"
  no_log: true

- name: Test Sudo Access
  become: true
  ansible.builtin.command:
    cmd: id -u

- name: Install passlib for password hashing
  become: true
  ansible.builtin.apt:
    name:
      - python3-passlib
    update_cache: true

- name: Change Interactive User Password
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ secrets.new_password | password_hash('sha512') }}"

- name: Get Sudo Password
  ansible.builtin.set_fact:
    ansible_become_password: "{{ secrets.new_password }}"

- name: Add Interactive User to Sudoers
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ ansible_user }}"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: true

- name: Setup SSH
  ansible.builtin.include_role:
    name: ssh
