- name: Create Interactive User SSH Directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user }}"

- name: Copy SSH Private Keys
  ansible.builtin.copy:
    content: "{{ secrets.ssh_key }}"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519"
    mode: "0600"
    owner: "{{ ansible_user }}"

- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "https://github.com/{{ secrets.git.gh_user }}.keys"

- name: Set SSH to Key Only
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: "#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: 'Restart SSHD'
