- name: Validate Tailscale credentials
  ansible.builtin.include_tasks: validate.yml

- name: Install tailscale
  ansible.builtin.include_tasks: install.yml

- name: Configure Tailscale
  ansible.builtin.include_tasks: configure.yml

- name: Authorize Tailscale
  ansible.builtin.include_tasks: authorize.yml

- name: Cleanup sensitive data
  ansible.builtin.include_tasks: cleanup.yml
