---
# GitHub Actions Runner defaults
github_runner_user: "runner"
github_runner_group: "runner"
github_runner_home: "/home/{{ github_runner_user }}"
github_runner_work_dir: "{{ github_runner_home }}/actions-runner"
github_runner_labels: "self-hosted,Linux,X64"
github_runner_name: "{{ ansible_hostname }}-runner"
github_runner_group_name: "static"
