---
- name: Install NUT
  hosts: pve:servers
  gather_facts: true
  vars:
    nut_mode: "{{ nut.mode | default('netserver') }}"
    nut_ups_name: "{{ nut.ups_name | default(ansible_hostname) }}"
    nut_monitor_host: "{{ nut.monitor_host | default('localhost') }}"
    nut_upsmon_role: "{{ nut.upsmon_role | default('primary') }}"
    nut_finaldelay: "{{ nut.finaldelay | default(300) }}"
  roles:
    - nut

