---
# - name: Security Setup
#   hosts: serversup
#   gather_facts: false
#   vars:
#     ansible_python_interpreter: "/usr/bin/python3"
#   roles:
#     - security
#     - pre-reqs


- name: Basic Setup
  hosts: servers
  gather_facts: true
  vars:
    tailscale_client_id: "{{secrets.tailscale.servers_client_id}}"
    tailscale_client_secret: "{{secrets.tailscale.servers_client_secret}}"
  roles:
    # - patch
    # - starship
    - nut
    # - tailscale
    - docker
