---
- name: Security Setup
  hosts: servers
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
  roles:
    - security
    - pre-reqs

- name: Basic Setup
  hosts: servers
  gather_facts: true
  vars:
    k3s_force_uninstall: false
  roles:
    - secondary-storage
    - patch
    - starship
    - nut
    - tailscale
    - github-runner
    - k3s-install
